name: Pull Request

on: pull_request

env:
  node-version: 16.13
jobs:
  test:
    name: "Tests"
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: "npm" # cache ~/.npm in case 'npm ci' needs to run

      - name: Install workerd Dependencies
        if: ${{ runner.os == 'Linux' }}
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get install -y libc++1

      # If the cache missed then install using `npm ci` to follow package lock exactly
      - name: Install NPM Dependencies
        run: npm ci

      - if: ${{ runner.os == 'Windows' }}
        name: Use `workerd` debug build
        run: |
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest "https://drive.google.com/uc?export=download&id=1cBCtdKCzoMvJe2L3R2aOulhv0LjKQKo0&confirm=t&uuid=9a943fb4-acad-46ee-9c17-3275f3c2d832&at=AB6BwCAp4KOLgwCpwk3K7XSPgqoV:1692742133153" -OutFile workerd-debug.zip
          Expand-Archive -Force -Path .\workerd-debug.zip -DestinationPath .\packages\wrangler\node_modules\@cloudflare\workerd-windows-64\bin\

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true

      - name: Run builds
        run: npm run build
        env:
          NODE_ENV: "production"

      - name: Run tests & collect coverage
        run: npm run test:ci -- --force
        env:
          TMP_CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          TMP_CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          NODE_OPTIONS: "--max_old_space_size=8192"

      - name: Report Code Coverage
        uses: codecov/codecov-action@v3
